jobs:
  include:
    - stage: test
      language: python
      python:
        - "3.7"
      install:
        - pip install -r travis-requirements.txt
      script:
        - cd src/classscribe-fe
        - npm install
        #- npm run build
        - cd ..
        - cd classscribe
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py test
    - stage: test
      language: node_js
      node_js:
        - 'stable'
      addons:
        apt:
          packages:
            - libgconf-2-4
      cache:
        npm: true
        directories:
          - ~/.cache
      before_install:
        - cd src/classscribe-fe
        - npm install
        #- npm run build
#         - npm start --silent &
        - npm install react-dom 
      script:
        #- npm run start
        - npm run test
#         - npm run tests
#         - kill $(jobs -p) || true
