language: python
python:
  - "3.7"
install:
  - pip install -r travis-requirements.txt
script:
  - python ~\src\classscribe\manage.py makemigrations
  - python ~\src\classscribe\manage.py migrate
  - python ~\src\classscribe\manage.py test