jobs:
  include:
    - stage: test
      language: python
      python:
        - "3.7"
      install:
        - pip install -r travis-requirements.txt
      script:
        - cd src/classscribe
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py test
    - stage: test
      language: node_js
      node_js:
        - '10'
      before_install:
        - cd src/classscribe-fe
      install:
        - npm ci
        - npm run build
      script:
        - npm run test
  