jobs:
  include:
    - language: python
      python:
        - "3.7"
      install:
        - pip install -r travis-requirements.txt
      script:
        - cd src/classscribe-fe
        - npm install
        #- npm run build
        - cd ..
        - cd classscribe
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py test
    - language: node_js
      node_js:
        - 'stable'
      cache:
        directories:
          - node_modules
      before_script:
        - cd src/classscribe
        - python manage.py runserver 127.0.0.1:8000 &
        - cd ..  
        - cd classscribe-fe
        - npm install
        - npm run build
      script:
        - npm run test

