language: python
python:
  - "3.7"
install:
  - pip install -r travis-requirements.txt
script:
  - cd src/classscribe
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test